version: "3.7"

# compose fragment for development setups
# https://docs.docker.com/compose/extends/

services:

  inyoka-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "ubuntuusers.local:127.0.0.1"
      - "forum.ubuntuusers.local:127.0.0.1"
      - "paste.ubuntuusers.local:127.0.0.1"
      - "wiki.ubuntuusers.local:127.0.0.1"
      - "planet.ubuntuusers.local:127.0.0.1"
      - "ikhaya.ubuntuusers.local:127.0.0.1"
      - "static.ubuntuusers.local:127.0.0.1"
      - "media.ubuntuusers.local:127.0.0.1"
    environment:
      INYOKA_ADMIN_PASSWORD: secret
    command: >
      sh -c "
      /root/.venvs/inyoka/bin/python manage.py migrate &&
      /root/.venvs/inyoka/bin/python manage.py runserver 0.0.0.0:8080"
    ## TODO /root/.venvs/inyoka/bin/python manage.py create_superuser --username admin --password $INYOKA_ADMIN_PASSWORD --email 'admin@localhost'
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme
      - ./inyoka:/inyoka/code

  build_statics_theme:
    image: inyokaproject
    working_dir: /inyoka/theme
    command: >
      sh -c "
      apt-get install -y inotify-tools &&
      /root/.venvs/inyoka/bin/python setup.py develop &&
      npm install &&
      npm run watch"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme
