FROM docker.io/library/caddy:2.8.4-alpine

LABEL org.opencontainers.image.source=https://github.com/inyokaproject/docker-setup
LABEL org.opencontainers.image.title="Caddy (customized for Inyoka)"

COPY --from=inyokaproject /inyoka/code/inyoka/static-collected /srv/www/static/
COPY error_template.html /srv/www/templates/
