version: "3.7" # https://docs.docker.com/compose/compose-file/compose-versioning/

x-django:
  &default-django
  DJANGO_SETTINGS_MODULE: production_settings

x-django-secrets:
  &django-secrets
  secrets:
    - inyoka-postgres-password
    - inyoka-secret-key
    - inyoka-akismet-key
    - inyoka-sentry-dsn


services:
  postgres:
    # pin postgres major version to prevent unexpected database migrations
    # debian image is used, as alpine can have problems with locals
    # see https://github.com/docker-library/docs/blob/master/postgres/README.md#locale-customization
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: inyoka
      # TODO defines superuser name -> do not use superuser from inyoka?
      POSTGRES_USER: inyoka
      POSTGRES_PASSWORD_FILE: /run/secrets/inyoka-postgres-password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    # increase shared memory like recommended at https://github.com/docker-library/docs/blob/master/postgres/README.md#caveats
    shm_size: 256M
    # https://github.com/docker-library/postgres/blob/a83005b407ee6d810413500d8a041c957fb10cf0/14/bullseye/Dockerfile#L211-L213
    # https://www.postgresql.org/docs/14/server-start.html suggests no timeout
    stop_grace_period: 5m
    secrets:
      - inyoka-postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  database-migration:
#    image: inyokaproject
#    command: /root/.venvs/inyoka/bin/python manage.py migrate
#    environment:
#      << : *default-django
#    depends_on:
#      - postgres
#    profiles:
#      - maintenance

  inyoka-worker:
    << : *django-secrets
    image: inyokaproject
    restart: always
    expose:
      - "8000/tcp"
    environment:
      << : *default-django
    command: /root/.venvs/inyoka/bin/gunicorn -b 127.0.0.1:8000 --workers 8 --max-requests 500 inyoka.wsgi:application
    # TODO depends_on:

  # TODO in Docker the "Protected mode" is turned off by default. This means that if you expose the port outside of your host (e.g., via -p on docker run), it will be open without a password to anyone.
  redis:
    image: redis:alpine
    restart: always

  celeryworker:
    << : *django-secrets
    image: inyokaproject
    restart: always
    command: /root/.venvs/inyoka/bin/celery worker --app=inyoka --loglevel=INFO --concurrency=8
    environment:
      << : *default-django

  celerybeat:
    << : *django-secrets
    image: inyokaproject
    restart: always
    command: /root/.venvs/inyoka/bin/celery beat --app=inyoka --loglevel=INFO --schedule /volume/celerybeat-schedule/celerybeat-schedule
    environment:
      << : *default-django
    volumes:
      - celerybeat-schedule:/volume/celerybeat-schedule


secrets:
  inyoka-postgres-password:
    external: true
  inyoka-secret-key:
    external: true
  inyoka-akismet-key:
    external: true
  inyoka-sentry-dsn:
    external: true

# https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
volumes:
  celerybeat-schedule: {}
  postgres-data: {}
