version: "3.8"

# fragment for development setups
# https://docs.docker.com/compose/extends/

x-django:
  &default-django
  environment:
    DJANGO_SETTINGS_MODULE: development_settings
  configs:
    - source: inyoka-dev-config
      target: /inyoka/code/development_settings.py

services:

  inyoka-worker:
    << : *default-django
    user: ${SUDO_UID:?uid-needed}:${SUDO_GID:?gid-needed}
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "ubuntuusers.localhost:127.0.0.1"
      - "forum.ubuntuusers.localhost:127.0.0.1"
      - "paste.ubuntuusers.localhost:127.0.0.1"
      - "wiki.ubuntuusers.localhost:127.0.0.1"
      - "planet.ubuntuusers.localhost:127.0.0.1"
      - "ikhaya.ubuntuusers.localhost:127.0.0.1"
      - "static.ubuntuusers.localhost:127.0.0.1"
      - "media.ubuntuusers.localhost:127.0.0.1"
    command: >
      sh -c "
      /inyoka/venv/bin/python manage.py migrate &&
      /inyoka/venv/bin/gunicorn -b 0.0.0.0:8000 --reload --workers 1 inyoka.wsgi:application"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme
      - ./inyoka:/inyoka/code

  celeryworker:
    << : *default-django

  celerybeat:
    << : *default-django

  build_statics_theme:
    image: inyokaproject
    user: root:root
    working_dir: /inyoka/theme
    command: >
      sh -c "
      apt-get install -y --no-install-recommends nodejs npm inotify-tools &&
      /inyoka/venv/bin/python setup.py develop &&
      npm install &&
      setpriv --reuid=${SUDO_UID:?uid} --regid=${SUDO_GID:?gid} --clear-groups sh -c 'npm run watch'"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme

  smtpd:
    image: inyokaproject
    command: python3 -m smtpd --debug --nosetuid --class DebuggingServer 0.0.0.0:1025


configs:
  inyoka-dev-config:
    file: ./development_settings.py
    template_driver: golang

