version: "3.8"

# fragment for development setups
# https://docs.docker.com/compose/extends/

x-django:
  &default-django
  user: root:root
  environment:
    DJANGO_SETTINGS_MODULE: development_settings
  configs:
    - source: inyoka-dev-config
      target: /inyoka/code/development_settings.py

services:

  inyoka-worker:
    << : *default-django
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "ubuntuusers.localhost:127.0.0.1"
      - "forum.ubuntuusers.localhost:127.0.0.1"
      - "paste.ubuntuusers.localhost:127.0.0.1"
      - "wiki.ubuntuusers.localhost:127.0.0.1"
      - "planet.ubuntuusers.localhost:127.0.0.1"
      - "ikhaya.ubuntuusers.localhost:127.0.0.1"
      - "static.ubuntuusers.localhost:127.0.0.1"
      - "media.ubuntuusers.localhost:127.0.0.1"
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      /inyoka/venv/bin/python manage.py migrate &&
      chown ${SUDO_UID:?uid}:${SUDO_GID:?gid} inyoka.log celery.log &&
      setpriv --reuid=${SUDO_UID:?uid} --regid=${SUDO_GID:?gid} --clear-groups /inyoka/venv/bin/gunicorn -b 0.0.0.0:8000 --reload --workers 1 inyoka.wsgi:application"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme
      - ./inyoka:/inyoka/code

  celeryworker:
    << : *default-django
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      chown ${SUDO_UID:?uid}:${SUDO_GID:?gid} inyoka.log celery.log &&
      setpriv --reuid=${SUDO_UID:?uid} --regid=${SUDO_GID:?gid} --clear-groups /inyoka/venv/bin/celery worker --app=inyoka --loglevel=INFO --concurrency=8"

  celerybeat:
    << : *default-django
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      chown ${SUDO_UID:?uid}:${SUDO_GID:?gid} inyoka.log celery.log &&
      setpriv --reuid=${SUDO_UID:?uid} --regid=${SUDO_GID:?gid} --clear-groups /inyoka/venv/bin/celery beat --app=inyoka --pidfile /tmp/celerybeat.pid --loglevel=INFO --schedule /tmp/celerybeat-schedule"

  build_statics_theme:
    image: inyokaproject
    user: root:root
    working_dir: /inyoka/theme
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends nodejs npm inotify-tools &&
      /inyoka/venv/bin/python setup.py develop &&
      npm install &&
      setpriv --reuid=${SUDO_UID:?uid} --regid=${SUDO_GID:?gid} --clear-groups npm run watch"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme

  # TODO let caddy serve new statics generated by build_statics

  smtpd:
    image: inyokaproject
    command: python3 -m smtpd --debug --nosetuid --class DebuggingServer 0.0.0.0:1025


configs:
  inyoka-dev-config:
    file: ./development_settings.py
    template_driver: golang

