# fragment for development setups
# https://docs.docker.com/compose/extends/

x-django:
  &default-django
  user: root:root
  environment:
    DJANGO_SETTINGS_MODULE: development_settings
  configs:
    - source: inyoka-dev-config
      target: /inyoka/code/development_settings.py
  volumes:
    - ./theme-ubuntuusers:/inyoka/theme
    - ./inyoka:/inyoka/code

x-user:
  &user-ids
  environment:
    INYOKA_GID: 100
    INYOKA_UID: 1000

services:

  inyoka-worker:
    << : *default-django
    << : *user-ids
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "ubuntuusers.localhost:127.0.0.1"
      - "forum.ubuntuusers.localhost:127.0.0.1"
      - "paste.ubuntuusers.localhost:127.0.0.1"
      - "wiki.ubuntuusers.localhost:127.0.0.1"
      - "planet.ubuntuusers.localhost:127.0.0.1"
      - "ikhaya.ubuntuusers.localhost:127.0.0.1"
      - "static.ubuntuusers.localhost:127.0.0.1"
      - "media.ubuntuusers.localhost:127.0.0.1"
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      /inyoka/venv/bin/python manage.py migrate &&
      chown $$INYOKA_UID:$$INYOKA_GID inyoka.log celery.log /srv/www/media &&
      setpriv --reuid=$$INYOKA_UID --regid=$$INYOKA_GID --clear-groups /inyoka/venv/bin/gunicorn -b 0.0.0.0:8000 --reload --workers 1 inyoka.wsgi:application"

  celeryworker:
    << : *default-django
    << : *user-ids
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      chown $$INYOKA_UID:$$INYOKA_GID inyoka.log celery.log &&
      setpriv --reuid=$$INYOKA_UID --regid=$$INYOKA_GID --clear-groups /inyoka/venv/bin/celery --app=inyoka worker --loglevel=INFO --concurrency=8"

  celerybeat:
    << : *default-django
    << : *user-ids
    command: >
      sh -c "
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      chown $$INYOKA_UID:$$INYOKA_GID inyoka.log celery.log /volume/celerybeat-schedule/ &&
      setpriv --reuid=$$INYOKA_UID --regid=$$INYOKA_GID --clear-groups /inyoka/venv/bin/celery --app=inyoka beat --pidfile /tmp/celerybeat.pid --loglevel=INFO --schedule /tmp/celerybeat-schedule"

  build_statics_theme:
    << : *user-ids
    image: git.ubuntu-eu.org/ubuntuusers/inyokaproject
    user: root:root
    working_dir: /inyoka/theme
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends nodejs npm inotify-tools &&
      npm install &&
      setpriv --reuid=$$INYOKA_UID --regid=$$INYOKA_GID --clear-groups npm run watch"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme

  copy_statics:
    image: git.ubuntu-eu.org/ubuntuusers/inyokaproject
    << : *default-django
    << : *user-ids
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends inotify-tools &&
      /inyoka/venv/bin/pip install --no-deps --require-hashes -r extra/requirements/development.txt &&
      chown $$INYOKA_UID:$$INYOKA_GID inyoka.log celery.log &&
      setpriv --reuid=$$INYOKA_UID --regid=$$INYOKA_GID --clear-groups bash -c 'while true; do /inyoka/venv/bin/python manage.py collectstatic --noinput --clear; inotifywait --quiet --recursive --event modify /inyoka/theme/inyoka_theme_ubuntuusers/static/; done'"
    volumes:
      - ./theme-ubuntuusers:/inyoka/theme:ro
      - ./inyoka/inyoka/static-collected:/inyoka/code/inyoka/static-collected
    configs:
      - source: inyoka-config
        target: /inyoka/code/production_settings.py
      - source: inyoka-dev-config
        target: /inyoka/code/development_settings.py
      - inyoka-base-domain
      - inyoka-media-domain
      - inyoka-static-domain
    secrets:
      - inyoka-postgres-password
      - inyoka-redis-password
      - inyoka-secret-key
      - inyoka-akismet-key
      - inyoka-sentry-dsn

  caddy:
   volumes:
     - ./inyoka/inyoka/static-collected:/srv/www/static/:ro

  smtpd:
    image: git.ubuntu-eu.org/ubuntuusers/inyokaproject
    command: python3 -m smtpd --debug --nosetuid --class DebuggingServer 0.0.0.0:1025


configs:
  inyoka-dev-config:
    file: ./development_settings.py
    template_driver: golang

